// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgApp.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420223142_UpdateCardSchema")]
    partial class UpdateCardSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgApp.Domain.Entities.BinderScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConfirmedCards")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProcessedImages")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalDetectedCards")
                        .HasColumnType("integer");

                    b.Property<int>("TotalImages")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("BinderScans");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BulkDataTimestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Cmc")
                        .HasColumnType("numeric");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ManaCost")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PricesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BulkDataTimestamp");

                    b.HasIndex("Cmc");

                    b.HasIndex("Colors");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ImageUrisJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ImageUrisJson"), "gin");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cards_Name_FTS")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");

                    b.HasIndex("OracleId");

                    b.HasIndex("PricesJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PricesJson"), "gin");

                    b.HasIndex("Rarity");

                    b.HasIndex("SetCode");

                    b.HasIndex("TypeLine");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Format");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.DeckCard", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<string>("ScryfallId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("IsMainboard")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("DeckId", "ScryfallId", "IsMainboard");

                    b.HasIndex("ScryfallId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.DetectedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BinderScanId")
                        .HasColumnType("integer");

                    b.Property<double>("BoundingBoxHeight")
                        .HasPrecision(8, 4)
                        .HasColumnType("double precision");

                    b.Property<double>("BoundingBoxWidth")
                        .HasPrecision(8, 4)
                        .HasColumnType("double precision");

                    b.Property<double>("BoundingBoxX")
                        .HasPrecision(8, 4)
                        .HasColumnType("double precision");

                    b.Property<double>("BoundingBoxY")
                        .HasPrecision(8, 4)
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid");

                    b.Property<double>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CorrectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CorrectedCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorrectedSet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetectedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DetectedSet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsManuallyVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ScanImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("UseForTraining")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BinderScanId");

                    b.HasIndex("CardId");

                    b.HasIndex("ConfidenceScore");

                    b.HasIndex("CorrectedCardId");

                    b.HasIndex("DetectedName");

                    b.HasIndex("ScanImageId");

                    b.HasIndex("Status");

                    b.ToTable("DetectedCards");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.ScanImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BinderScanId")
                        .HasColumnType("integer");

                    b.Property<int>("DetectedCardCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("ProcessingDuration")
                        .HasColumnType("interval");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProcessingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BinderScanId");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedAt");

                    b.ToTable("ScanImages");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.DeckCard", b =>
                {
                    b.HasOne("MtgApp.Domain.Entities.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.DetectedCard", b =>
                {
                    b.HasOne("MtgApp.Domain.Entities.BinderScan", "BinderScan")
                        .WithMany("DetectedCards")
                        .HasForeignKey("BinderScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgApp.Domain.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MtgApp.Domain.Entities.Card", "CorrectedCard")
                        .WithMany()
                        .HasForeignKey("CorrectedCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MtgApp.Domain.Entities.ScanImage", "ScanImage")
                        .WithMany("DetectedCards")
                        .HasForeignKey("ScanImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinderScan");

                    b.Navigation("Card");

                    b.Navigation("CorrectedCard");

                    b.Navigation("ScanImage");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.ScanImage", b =>
                {
                    b.HasOne("MtgApp.Domain.Entities.BinderScan", "BinderScan")
                        .WithMany("Images")
                        .HasForeignKey("BinderScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinderScan");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.BinderScan", b =>
                {
                    b.Navigation("DetectedCards");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("MtgApp.Domain.Entities.ScanImage", b =>
                {
                    b.Navigation("DetectedCards");
                });
#pragma warning restore 612, 618
        }
    }
}
